secrets:
    default:
        env:
            DB_URL: ENC[AES256_GCM,data:45rQVH1Qn6txhuR6UtqEGwq0LhMD1ozlsYUQ2BsDsfebQNiKxu772uRv2dgQ4clP8HQHBLP7B49/cuH0Ia1HTnz8/IxKYq0F11MtivCUxn78BDeKdTC+uttj071PGhLjYgd4vXRuk1yanqvgdyILIpHy3/3X29hePWjYANHMTewkKXqwPAGpcMSgsg+A2wz/+KHM5hEwo/nZgkZd47trvh9i1q8E1+cKBrRCn03KUA==,iv:UFRHQz7F8krqmVOh03pCKeRXiy/sj8e6MpUCEpNS3qk=,tag:AVz11bqdQGB19jyPMQQalA==,type:str]
            ENCRYPTION_SECRET: ENC[AES256_GCM,data:OOHm69AmPwoSVbKc24wldCSUFLapEsJCrJY66d6hYkYboA/ZTgwntrq/TfWB0ITi843JxpYxmgjtlSD9A1DLOQ37DYBSrhbI/NRKsDpMgEQOVewMDInICmQ7qAntaYYYYpIXhlq5OWkBSKXfyeqqTgGa7SXytKQEFghlVAp48KI=,iv:6squmQdR1ogWEhUroFnjMPfyOeksmX6Q2OXT3GIsLls=,tag:Tv/R7vUjm2PcMpfquUdbzg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-1:594234444642:alias/staff-engineers
          aws_profile: ""
          created_at: "2026-06-27T07:29:07Z"
          enc: AQICAHh8H0ntgAwshEGIChG/SfCF6fWY1NmU22C0Lgqzu6vaHAFiDOePdHyR8UsgUrwEOrZFAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMuaVe/7CJpeBnXT1VAgEQgDt4PphEmog3/1A7kWDaGUwhRI61LNmHrSlq2WrRIlwGzeIkDaMFmOQjHbT9MxxgH5RbHMK78Wqcl+1RbA==
        - arn: arn:aws:kms:eu-central-1:594234444642:alias/staff-engineers
          aws_profile: ""
          created_at: "2026-06-27T07:29:07Z"
          enc: AQICAHgnbJRCM6V+G7IGKndAH4Xp4WRQpALLInSrmAJixP2bjQF9xVDwTBs5N9WOQZ4n2kIxAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMvUWyq7OpkmNVXiAWAgEQgDsynnmjvNO/TvTEBSQiOG4IDLj81oCh1A2Dzn9DE7xfQRW16G+jObJUkY9XoDwvs13wMYg4ElKM9F8wAw==
        - arn: arn:aws:kms:eu-west-1:126368329757:alias/cicd-key
          aws_profile: ""
          created_at: "2026-06-27T07:29:07Z"
          enc: AQICAHi9Q3amv/qeWrBsqWoce3uvW6kbymNHPhQgFQ/ZjB6TjwF8FQC4GNBQ9JVzMnMQwlGJAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMNSoxucfri8TNw98eAgEQgDs5eyeStcQjo9Wjrldvr2BEJYtpq/Zgwwk65KqaQuxLLv86XFehKRzp3+Sn51BIHy+LbWaJL4iWIxpq2A==
        - arn: arn:aws:kms:eu-central-1:126368329757:alias/cicd-key
          aws_profile: ""
          created_at: "2026-06-27T07:29:07Z"
          enc: AQICAHirJYicl4QMeJ0UtEcdEvUEprcNjxNlEka1BAR6XGfbXQEw3WJa5HeVhRasGLRRdeaJAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMAPAbh+86QR9UumAiAgEQgDuLUhLGq2wPagk76FXICE1pYLyvrXpsQ3XV3473IwnHqPsNr4bbazdeoLQMcLavoq9iv9fTQcwz4t+24Q==
    lastmodified: "2026-06-27T07:29:11Z"
    mac: ENC[AES256_GCM,data:vPPnVrxVkXc+g7AGg/n4s2Mnwz+gS06EqLbcIFlT56pLSo5QknFtv1l6HP+cMXAxeWnsFfN9YGk7XQAox2Bfi6/KNtkJh5BZX39i93jaFJvaTSCRELwKhrivCMXcJdkQQLgeMHTWx3YO988/yhTmIZGy9WoWtju6BD9NVtQAOqs=,iv:SUdNlgroY2ik3cpfo4Yego8Xik8nPIdN6ylDgCtMW7k=,tag:8QH4kXAyL4XyRH0RQ4zI7w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
