{
 "title": "DORA Details - Failed Deployment Recovery Time",
 "tags": [ "DORA" ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Project",
    "query": "select distinct name from projects"
   },
   { "name": "author_type", "label": "Author Type", "query": "Human : 0, Bot : 1" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard shows the details about [Failed Deployment Recovery Time\n](https://devlake.apache.org/docs/Metrics/MTTR) in DORA."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "1. Failed Deployment Recovery Time",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "--  ***** 2023 report ***** --\n--  Metric 4: Failed deployment recovery time\nwith _deployments as (\n  SELECT\n    cdc.cicd_deployment_id as deployment_id,\n    max(cdc.finished_date) as deployment_finished_date\n  FROM\n    cicd_deployment_commits cdc\n    JOIN project_mapping pm on cdc.cicd_scope_id = pm.row_id\n    JOIN project_pr_metrics ppm on cdc.id = ppm.deployment_commit_id\n    and pm.`table` = 'cicd_scopes'\n  WHERE\n    pm.project_name in ($project)\n    and cdc.result = 'SUCCESS'\n    and cdc.environment = 'PRODUCTION'\n    and (ppm.is_authored_by_bot is null or ppm.is_authored_by_bot in (${author_type}))\n  GROUP BY\n    1\n  HAVING\n    $__timeFilter(max(cdc.finished_date))\n),\n_incidents_for_deployments as (\n  SELECT\n    i.id as incident_id,\n    i.created_date as incident_create_date,\n    i.resolution_date as incident_resolution_date,\n    fd.deployment_id as caused_by_deployment,\n    fd.deployment_finished_date,\n    date_format(fd.deployment_finished_date, '%y/%m') as deployment_finished_month\n  FROM\n    incidents i\n    left join project_incident_deployment_relationships pim on i.id = pim.id\n    join _deployments fd on pim.deployment_id = fd.deployment_id\n  WHERE\n    $__timeFilter(i.resolution_date)\n),\n_recovery_time_ranks as (\n  SELECT\n    *,\n    percent_rank() over(\n      order by\n        TIMESTAMPDIFF(\n          MINUTE,\n          deployment_finished_date,\n          incident_resolution_date\n        )\n    ) as ranks\n  FROM\n    _incidents_for_deployments\n),\n_median_recovery_time as (\n  SELECT\n    max(\n      TIMESTAMPDIFF(\n        MINUTE,\n        deployment_finished_date,\n        incident_resolution_date\n      )\n    ) as median_recovery_time\n  FROM\n    _recovery_time_ranks\n  WHERE\n    ranks <= 0.5\n),\n\n_is_collected_data as(\n  SELECT\n    CASE\n      WHEN NOT EXISTS(SELECT 1 FROM _deployments) AND NOT EXISTS(SELECT 1 FROM _incidents_for_deployments) THEN 'No deployments and incidents'\n      WHEN NOT EXISTS(SELECT 1 FROM _deployments) THEN 'No Deployments'\n      WHEN NOT EXISTS(SELECT 1 FROM _incidents_for_deployments) THEN 'No Incidents'\n      Else 'No incidents are mapped to deployments'\n    END AS is_collected\n)\n\nSELECT\n  CASE\n    WHEN is_collected = \"No deployments and incidents\" THEN \"N/A. Please check if you have collected deployments and incidents.\"\n    WHEN is_collected = \"No Deployments\" THEN \"N/A. Please check if you have collected deployments.\"\n    WHEN is_collected = \"No Incidents\" THEN \"N/A. Please check if you have collected incidents.\"\n    WHEN median_recovery_time is not null then median_recovery_time/60 \n    ELSE \"No data\"\n  END AS median_recovery_time_in_hours\nFROM\n  _median_recovery_time,\n  _is_collected_data"
    }
   ]
  },
  {
   "title": "3. Deployments and Incidents Details",
   "type": "table",
   "gridPos": { "h": 19, "w": 19, "x": 5, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "rawSql": "--  ***** 2023 report ***** --\n--  Metric 4: Failed deployment recovery time\nwith _deployments as (\n  SELECT\n    cdc.cicd_deployment_id as deployment_id,\n    max(cdc.finished_date) as deployment_finished_date\n  FROM\n    cicd_deployment_commits cdc\n    JOIN project_mapping pm on cdc.cicd_scope_id = pm.row_id\n    JOIN project_pr_metrics ppm on cdc.id = ppm.deployment_commit_id\n    and pm.`table` = 'cicd_scopes'\n  WHERE\n    pm.project_name in ($project)\n    and cdc.result = 'SUCCESS'\n    and cdc.environment = 'PRODUCTION'\n    and (ppm.is_authored_by_bot is null or ppm.is_authored_by_bot in (${author_type}))\n  GROUP BY\n    1\n  HAVING\n    $__timeFilter(max(cdc.finished_date))\n),\n_incidents_for_deployments as (\n  SELECT\n    fd.deployment_id as \"deployment_id\",\n    fd.deployment_finished_date,\n    -- date_format(fd.deployment_finished_date,'%y/%m') as deployment_finished_month,\n    i.id as incident_caused_by_deployment,\n    i.title as incident_title,\n    i.url as incident_url,\n    i.url as \"metric_hidden\",\n    -- i.created_date as incident_create_date,\n    i.resolution_date as incident_resolution_date,\n    TIMESTAMPDIFF(\n      HOUR,\n      fd.deployment_finished_date,\n      i.resolution_date\n    ) as \"failed_deployment_recovery_time\"\n  FROM\n    incidents i\n    left join project_incident_deployment_relationships pim on i.id = pim.id\n    join _deployments fd on pim.deployment_id = fd.deployment_id\n  WHERE\n    $__timeFilter(i.resolution_date)\n)\nselect\n  *\nFROM\n  _incidents_for_deployments\nwhere\n  incident_resolution_date IS NOT NULL"
    }
   ]
  },
  {
   "title": "2. The number of incidents caused by deployments",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "--  ***** 2023 report ***** --\n--  Metric 4: Failed deployment recovery time\nwith _deployments as (\n  SELECT\n    cdc.cicd_deployment_id as deployment_id,\n    max(cdc.finished_date) as deployment_finished_date\n  FROM\n    cicd_deployment_commits cdc\n    JOIN project_mapping pm on cdc.cicd_scope_id = pm.row_id\n    JOIN project_pr_metrics ppm on cdc.id = ppm.deployment_commit_id\n    and pm.`table` = 'cicd_scopes'\n  WHERE\n    pm.project_name in ($project)\n    and cdc.result = 'SUCCESS'\n    and cdc.environment = 'PRODUCTION'\n    and (ppm.is_authored_by_bot is null or ppm.is_authored_by_bot in (${author_type}))\n  GROUP BY\n    1\n  HAVING\n    $__timeFilter(max(cdc.finished_date))\n),\n_incidents_for_deployments as (\n  SELECT\n    i.id as incident_id,\n    i.created_date as incident_create_date,\n    i.resolution_date as incident_resolution_date,\n    fd.deployment_id as caused_by_deployment,\n    fd.deployment_finished_date,\n    date_format(fd.deployment_finished_date, '%y/%m') as deployment_finished_month\n  FROM\n    incidents i\n    left join project_incident_deployment_relationships pim on i.id = pim.id\n    join _deployments fd on pim.deployment_id = fd.deployment_id\n  WHERE\n    $__timeFilter(i.resolution_date)\n),\n--  ***** 2021 report ***** --\n-- Metric 4: Median time to restore service \n_incidents as (\n  -- get the incidents created within the selected time period in the top-right corner\n  SELECT\n    distinct i.id,\n    cast(lead_time_minutes as signed) as lead_time_minutes\n  FROM\n    incidents i\n    join project_mapping pm on i.scope_id = pm.row_id\n    and i.`table` = pm.`table`\n    and pm.`table` = 'boards'\n  WHERE\n    pm.project_name in (${project})\n    and $__timeFilter(i.created_date)\n)\nSELECT\n  COUNT(incident_id) AS total_count\nFROM\n  _incidents_for_deployments"
    }
   ]
  }
 ]
}