{
 "title": "DORA Details - Time to Restore Service",
 "tags": [ "DORA" ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Project",
    "query": "select distinct name from projects"
   },
   { "name": "author_type", "label": "Author Type", "query": "Human : 0, Bot : 1" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard shows the details about [Time to restore service\n](https://devlake.apache.org/docs/Metrics/MTTR) in DORA."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "1. Median Time to Restore Service",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "--  ***** 2021 report ***** --\n-- Metric 4: Median time to restore service \nwith _deployments as (\n  SELECT\n    cdc.cicd_deployment_id as deployment_id,\n    max(cdc.finished_date) as deployment_finished_date\n  FROM\n    cicd_deployment_commits cdc\n    JOIN project_mapping pm on cdc.cicd_scope_id = pm.row_id and pm.`table` = 'cicd_scopes'\n    JOIN project_pr_metrics ppm on cdc.id = ppm.deployment_commit_id\n  WHERE\n    pm.project_name in ($project)\n    and cdc.result = 'SUCCESS'\n    and cdc.environment = 'PRODUCTION'\n    and (ppm.is_authored_by_bot is null or ppm.is_authored_by_bot in (${author_type}))\n  GROUP BY\n    1\n  HAVING\n    $__timeFilter(max(cdc.finished_date))\n),\n_incidents as (\n  -- get the incidents created within the selected time period in the top-right corner\n  SELECT\n    distinct i.id,\n    cast(lead_time_minutes as signed) as lead_time_minutes\n  FROM\n    incidents i\n    left join project_incident_deployment_relationships pim on i.id = pim.id\n    join _deployments fd on pim.deployment_id = fd.deployment_id\n    join project_mapping pm on i.scope_id = pm.row_id\n    and pm.`table` = i.`table`\n  WHERE\n    pm.project_name in (${project})\n    and $__timeFilter(i.resolution_date)\n),\n_median_mttr_ranks as(\n  SELECT\n    *,\n    percent_rank() over(\n      order by\n        lead_time_minutes\n    ) as ranks\n  FROM\n    _incidents\n),\n_median_mttr as(\n  SELECT\n    max(lead_time_minutes) as median_time_to_resolve\n  FROM\n    _median_mttr_ranks\n  WHERE\n    ranks <= 0.5\n)\nSELECT\n  median_time_to_resolve / 60 AS median_time_to_resolve_in_hours\nFROM\n  _median_mttr"
    }
   ]
  },
  {
   "title": "3. Time to restore service details",
   "type": "table",
   "gridPos": { "h": 19, "w": 19, "x": 5, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "rawSql": "--  ***** 2021 report ***** --\n-- Metric 4: Median time to restore service \nwith _deployments as (\n  SELECT\n    cdc.cicd_deployment_id as deployment_id,\n    max(cdc.finished_date) as deployment_finished_date\n  FROM\n    cicd_deployment_commits cdc\n    JOIN project_mapping pm on cdc.cicd_scope_id = pm.row_id\n    JOIN project_pr_metrics ppm on cdc.id = ppm.deployment_commit_id\n    and pm.`table` = 'cicd_scopes'\n  WHERE\n    pm.project_name in ($project)\n    and cdc.result = 'SUCCESS'\n    and cdc.environment = 'PRODUCTION'\n    and (ppm.is_authored_by_bot is null or ppm.is_authored_by_bot in (${author_type}))\n  GROUP BY\n    1\n  HAVING\n    $__timeFilter(max(cdc.finished_date))\n),\n_incidents as (\n-- get the incidents created within the selected time period in the top-right corner\n  SELECT\n    distinct i.id as \"incident_id\",\n    i.title,\n    i.url,\n    i.url as \"metric_hidden\",\n    -- i.created_date,\n    i.resolution_date,\n    cast(lead_time_minutes/60 as signed) as time_to_restore_service\n  FROM\n    incidents i\n    left join project_incident_deployment_relationships pim on i.id = pim.id    \n    join project_mapping pm on i.scope_id = pm.row_id and pm.`table` = i.`table`\n    join _deployments fd on pim.deployment_id = fd.deployment_id\n  WHERE\n    pm.project_name in ($project)    \n    and $__timeFilter(i.resolution_date)\n)\n\nSELECT * \nFROM _incidents\nORDER BY resolution_date DESC"
    }
   ]
  },
  {
   "title": "2. Incident Count",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "--  ***** 2021 report ***** --\n-- Metric 4: Median time to restore service \nwith _deployments as (\n    SELECT\n        cdc.cicd_deployment_id as deployment_id,\n        max(cdc.finished_date) as deployment_finished_date\n    FROM \n        cicd_deployment_commits cdc\n        JOIN project_mapping pm on cdc.cicd_scope_id = pm.row_id and pm.`table` = 'cicd_scopes'\n        JOIN project_pr_metrics ppm on cdc.id = ppm.deployment_commit_id\n    WHERE\n        pm.project_name in ($project)\n        and cdc.result = 'SUCCESS'\n        and cdc.environment = 'PRODUCTION'\n        and (ppm.is_authored_by_bot is null or ppm.is_authored_by_bot in (${author_type}))\n    GROUP BY 1\n    HAVING $__timeFilter(max(cdc.finished_date))\n),\n\n_incidents as (\n-- get the incidents created within the selected time period in the top-right corner\n  SELECT\n    distinct i.id,\n    cast(lead_time_minutes as signed) as lead_time_minutes\n  FROM\n    incidents i    \n    join project_mapping pm on i.scope_id = pm.row_id and pm.`table` = i.`table`\n    join project_incident_deployment_relationships pim on i.id = pim.id\n    join _deployments fd on pim.deployment_id = fd.deployment_id\n\n  WHERE\n    pm.project_name in (${project})\n    and $__timeFilter(i.created_date)\n)\n\nSELECT\n    COUNT(id) AS \"incident count\"\nFROM\n    _incidents\n\n"
    }
   ]
  }
 ]
}