secrets:
    default:
        env:
            MYSQL_PASSWORD: ENC[AES256_GCM,data:2c2LQ+ZHL7dtiFnJvAOJGw==,iv:/Ai56Y7YNjn+60+KfJxbshfhABVkta2oJoOTf3fXb5k=,tag:eOEPlWy7FE4RLpRHuYPHkQ==,type:str]
            GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:JUFzouwo/OHlQX1Ig3iEJg==,iv:rXL+NUDgOfZAG+1w8078oTwITfY71xIkA79TCyG1WME=,tag:sUYlccdyyY2ED/c5P9tUKw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-1:594234444642:alias/staff-engineers
          aws_profile: ""
          created_at: "2026-06-27T07:29:27Z"
          enc: AQICAHh8H0ntgAwshEGIChG/SfCF6fWY1NmU22C0Lgqzu6vaHAEZBj2xppyzF06z52rn0l81AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMtDa+ukCAgR1je0F3AgEQgDskay6eY0DfQC6n2t3PxikFsbfjpVuefNt20QqBTLLobl8sRY3Xf9otmBpDWrjYcHN3TINazKnYqprGaw==
        - arn: arn:aws:kms:eu-central-1:594234444642:alias/staff-engineers
          aws_profile: ""
          created_at: "2026-06-27T07:29:27Z"
          enc: AQICAHgnbJRCM6V+G7IGKndAH4Xp4WRQpALLInSrmAJixP2bjQE1UviJajqyQQUn0ypUZqAZAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM1CWwMZAKDS2LETPBAgEQgDs/TXkZPdwUcv2hZED8zkOlVhibvGAOxz9vmOGiRLpE7NsUTJs+nBKKYs+1N6nSUYMyUDTD13VsOvCsow==
        - arn: arn:aws:kms:eu-west-1:126368329757:alias/cicd-key
          aws_profile: ""
          created_at: "2026-06-27T07:29:27Z"
          enc: AQICAHi9Q3amv/qeWrBsqWoce3uvW6kbymNHPhQgFQ/ZjB6TjwF9ZTBjP28vRFVF0k0GdBI8AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM0FNsnMPPmV+/c2ZnAgEQgDuQg3hUuvui/uCBTXubYk2p8ZSPDn5Bbn3hcUKRSfHpJy27xGpvolk7rO+9EJJbw6XLR+BhZ+K1R3ko2A==
        - arn: arn:aws:kms:eu-central-1:126368329757:alias/cicd-key
          aws_profile: ""
          created_at: "2026-06-27T07:29:27Z"
          enc: AQICAHirJYicl4QMeJ0UtEcdEvUEprcNjxNlEka1BAR6XGfbXQEBoPDoBJ0XJH3imZJRunxJAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMeC4VF7tLplavtcT4AgEQgDv+1K7j1nbjC9an4YTzJhXsdLAryI5daJ/AhR7BUAACzHeGp9DL4dcjvtFLwN32tSs9JC2XyV84j2irWA==
    lastmodified: "2026-06-27T07:29:30Z"
    mac: ENC[AES256_GCM,data:xoKu4UC9wFmELFjUuGjmtNZLb89lnh8so1mqxSWuU2OXOgEnguTq109+kTTORT1X4Dtt3mMKySLG7voCK0MdpCxMz0Iy+O+okID4Tzfe19KtNDB7DAhaJRRlom2ObYeJy9Q4wkpiQEC1dPKLzAZDdgxlPHFFkd8UfPlInVwQxxk=,iv:w+CfL8hGmGHGt/IyCOqaQ6i30BUgMUKTD4BJDLkxHmY=,tag:vhvkt/9N50Nw6uBf2xFW6Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
